/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pemvis2.project1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lenovo
 */
public class addCustomer extends javax.swing.JFrame {

    /**
     * Creates new form addCustomer
     */
    public addCustomer(String sendData) {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x=screen.width/2-this.getSize().width/2;
        int y=screen.height/2-this.getSize().height/2;
        this.setLocation(x,y);
        if(sendData!=""){
           String sqlQuery="SELECT* FROM PELANGGAN WHERE id_pelanggan = '"+sendData+"'";
           try{
               Class.forName("com.mysql.cj.jdbc.Driver");
             Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");    
             PreparedStatement pst=conn.prepareStatement(sqlQuery);
             ResultSet rs =pst.executeQuery();
             if(rs.next()){
                 String id=rs.getString(1);
                 String name=rs.getString(2);
                 String gender=rs.getString(3);
                 String address=rs.getString(4);
                 String phone=rs.getString(5);
                 String bday=rs.getString(6);
                 String type=rs.getString(7);
                 
                 if(gender.equals("L"))
                     gender="Laki-laki";
                 else
                     gender="Perempuan";
                 
                 if(type.equals("G"))
                     type="Gold";
                 else
                     type="Silver";
                 
                 txt_id.setText(id);
                 txt_name.setText(name);
                 cb_gender.setSelectedItem(gender);
                 txt_address.setText(address);
                 txt_bday.setText(bday);
                 txt_phone.setText(phone);
                 cb_type.setSelectedItem(type);
                 
                 txt_id.setEditable(false);
                 txt_name.setEditable(false);
                 cb_gender.setEnabled(false);
                 txt_address.setEditable(false);
                 txt_bday.setEditable(false);
                 txt_phone.setEditable(false);
                 cb_type.setEnabled(false);
                 
                 add_btn.setText("Update??");
                         
             }
             
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
        }
        /*else{
            String countQuery = "Select count(id_pelanggan 'jumlah' from pelanggan";
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");    
                PreparedStatement pst=conn.prepareStatement(countQuery);
                ResultSet rs =pst.executeQuery();
                if(rs.next()){
                    int totalCstmr = Integer.parseInt(rs.getString(1))+1;
                    String id;
                    if(totalCstmr<10)
                        id="P00"+String.valueOf(totalCstmr);
                    else if(totalCstmr<100)
                        id="P0"+String.valueOf(totalCstmr);
                    else
                        id="P"+String.valueOf(totalCstmr);
                    
                    txt_id.setText(id);
                    txt_id.setEditable(false);
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_gender = new javax.swing.JComboBox<>();
        txt_address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_bday = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_type = new javax.swing.JComboBox<>();
        cancel_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Customer");

        jLabel2.setText("Name");

        jLabel3.setText("Gender");

        cb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel4.setText("Address");

        jLabel5.setText("Phone");

        jLabel6.setText("BirthDay");

        jLabel7.setText("Type");

        cb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gold", "Silver" }));

        cancel_btn.setBackground(new java.awt.Color(255, 102, 102));
        cancel_btn.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setText("cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        add_btn.setBackground(new java.awt.Color(51, 204, 255));
        add_btn.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("Add");
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel_btn)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bday, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_bday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_btn)
                    .addComponent(add_btn))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        new Pelanggan().setVisible(true);
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        
        if(add_btn.getText().equals("Add")){
            String id= txt_id.getText();
            String name= txt_name.getText();
            String gender= cb_gender.getSelectedItem().toString();
            String address= txt_address.getText();
            String bday= txt_bday.getText();
            String phone= txt_phone.getText();
            String type= cb_type.getSelectedItem().toString();
            
            /*if(!name.isEmpty()||!id.isEmpty()){
                int confirm=JOptionPane.showConfirmDialog(null, "Add new Data?","Add Data", JOptionPane.YES_NO_OPTION);
            }if(confirm==JOptionPane.YES_OPTION){
                
            }*/
        
            if(gender=="M")
                gender="L";
            else
                gender="P";

            if(type == "Gold")
                type="G";
            else
                type="S";
            //('id_pelanggan,'nama','jenis_kelamin','alamat','telepon','tgl_lahir','jenis_pelanggan' )
            String addQuery="INSERT INTO pelanggan values ('"+ id +"','"+ name + "','" + gender + "','" + address + "','" + phone + "','" + bday + "','" + type + "')";

            /*try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
                 Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");    
                 PreparedStatement pst=conn.prepareStatement(addQuery);
                 pst.execute();
                 JOptionPane.showMessageDialog(null,"Success");
                 dispose();
                 new Pelanggan().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }*/
            int checkData;
        if(!name.isEmpty()){
            int choices=JOptionPane.showConfirmDialog(null, "Add new Data?","Add Data", JOptionPane.YES_NO_OPTION);
            if(choices==JOptionPane.YES_OPTION){
                try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
                 Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");    
                 PreparedStatement pst=conn.prepareStatement(addQuery);
                 pst.execute();
                 JOptionPane.showMessageDialog(null,"Success");
                 dispose();
                 new Pelanggan().setVisible(true);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }else
            checkData=JOptionPane.showConfirmDialog(null,"Please enter the name","Empty Name",JOptionPane.DEFAULT_OPTION);
        
        }else if(add_btn.getText().equals("Update??")){
            txt_id.setEditable(true);
            txt_name.setEditable(true);
            cb_gender.setEnabled(true);
            txt_address.setEditable(true);
            txt_bday.setEditable(true);
            txt_phone.setEditable(true);
            cb_type.setEnabled(true);
            
            add_btn.setText("Update");
        }else if(add_btn.getText().equals("Update")){
            String gender=cb_gender.getSelectedItem().toString();
            String type=cb_type.getSelectedItem().toString();
            if(gender=="M")
                gender="L";
            else
                gender="P";

            if(type == "Gold")
                type="G";
            else
                type="S";
            
            String updateQuery=" UPDATE pelanggan set nama = '"+
                    txt_name.getText()+"',jenis_kelamin = '"+gender+"', alamat= '"+txt_address.getText()+
                    "', telepon = '"+txt_phone.getText()+"', tgl_lahir= '"+txt_bday.getText()+"', jenis_pelanggan = '"+type+"' where id_pelanggan = '"+txt_id.getText()+"' ";
            try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");    
             PreparedStatement pst=conn.prepareStatement(updateQuery);
             pst.execute();
             JOptionPane.showMessageDialog(null,"Success");
             dispose();
             new Pelanggan().setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            
        }
        else{
            String countQuery = "Select count(id_pelanggan 'jumlah' from pelanggan";
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");    
                PreparedStatement pst=conn.prepareStatement(countQuery);
                ResultSet rs =pst.executeQuery();
                if(rs.next()){
                    int totalCstmr = Integer.parseInt(rs.getString(1))+1;
                    String id;
                    if(totalCstmr<10)
                        id="P00"+String.valueOf(totalCstmr);
                    else if(totalCstmr<100)
                        id="P0"+String.valueOf(totalCstmr);
                    else
                        id="P"+String.valueOf(totalCstmr);
                    
                    txt_id.setText(id);
                    txt_id.setEditable(false);
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
        
        
        
        
            
        
    }//GEN-LAST:event_add_btnActionPerformed

    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new addCustomer("").setVisible(true);
                addCustomer sendData=new addCustomer(null);
                sendData.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JComboBox<String> cb_gender;
    private javax.swing.JComboBox<String> cb_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_bday;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
